void iniciar(void);
void terminar(void);
int declarar(char* id);
void asignar(char* id);
void leer(char* id);
void escribir(char* id);
int existe_identificador(char* id);
void generar_infijo(int op, char* id1, char* id2);
void generar_unario(char* id);
bool contiene_nodo(char* id);
